package co.insou.radio.gui.page;

/**
 * Created by insou on 10/01/2016.
 */
public enum ExternalIgnorance {

    // GIVE EACH CALL OF EXTERNAL IGNORE A SPECIFIC ENUM TO WORK AGAINST IN A LIST, AND USE CONTAINS / REMOVE TO CHECK FOR IGNORE
    CLICKINV_OPEN_INV,
    CLICKINV_DISPLAY_INVENTORY,
    PAGE_INVENTORY_CLICK, CREATE_REGION, NAME_EDIT_CREATE,

}
